# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65b8f3536342e7c6b6de65dd91c0bda6bd327d30061bf69263f8104c884b83e69a4c9ba844c2992594d25613afa5841a379b4957152de595b7b0321f422482ca

test:
  secret_key_base: 6f9646a0ea144bf91b320f1cea3076ff6f9fc5484b1374a3830fd3abe2218bbccf3dd66f9ee2525802d1d29f15e5b842f4adf15aa942e9793e393c96a35ba934

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
